<div class='images-slider images-slider-hidden' id='main-slider'>
    <?
    // Список новостей - http://dev.1c-bitrix.ru/user_help/content/iblock/components_2/news/news_list.php
    $APPLICATION->IncludeComponent(
    	"bitrix:news.list",
    	"list-restaurants",
    	array(
    		"AJAX_MODE" => "N",
    		"IBLOCK_TYPE" => "dynamic_content",
    		"IBLOCK_ID" => "3",
    		"NEWS_COUNT" => "99",
    		"SORT_BY1" => "SORT",
    		"SORT_ORDER1" => "ASC",
    		"SORT_BY2" => "",
    		"SORT_ORDER2" => "",
    		"FILTER_NAME" => "",
    		"FIELD_CODE" => array(
    			0 => "",
    			1 => "",
    		),
    		"PROPERTY_CODE" => array(
    			0 => "",
    			1 => "",
    		),
    		"CHECK_DATES" => "Y",
    		"DETAIL_URL" => "",
    		"PREVIEW_TRUNCATE_LEN" => "",
    		"ACTIVE_DATE_FORMAT" => "d.m.Y",
    		"SET_TITLE" => "N",
    		"SET_STATUS_404" => "N",
    		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
    		"ADD_SECTIONS_CHAIN" => "Y",
    		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
    		"PARENT_SECTION" => "",
    		"PARENT_SECTION_CODE" => "",
    		"CACHE_TYPE" => "A",
    		"CACHE_TIME" => "36000000",
    		"CACHE_NOTES" => "",
    		"CACHE_FILTER" => "N",
    		"CACHE_GROUPS" => "Y",
    		"DISPLAY_TOP_PAGER" => "N",
    		"DISPLAY_BOTTOM_PAGER" => "N",
    		"PAGER_TITLE" => "Новости",
    		"PAGER_SHOW_ALWAYS" => "N",
    		"PAGER_TEMPLATE" => "",
    		"PAGER_DESC_NUMBERING" => "N",
    		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    		"PAGER_SHOW_ALL" => "N",
    		"AJAX_OPTION_JUMP" => "N",
    		"AJAX_OPTION_STYLE" => "Y",
    		"AJAX_OPTION_HISTORY" => "N",
    		"AJAX_OPTION_ADDITIONAL" => "",
    		"COMPONENT_TEMPLATE" => "list-restaurants",
    		"SET_BROWSER_TITLE" => "N",
    		"SET_META_KEYWORDS" => "N",
    		"SET_META_DESCRIPTION" => "N",
    		"SET_LAST_MODIFIED" => "N",
    		"INCLUDE_SUBSECTIONS" => "Y",
    		"PAGER_BASE_LINK_ENABLE" => "N",
    		"SHOW_404" => "N",
    		"MESSAGE_404" => ""
    	),
    	false
    );
    ?>
</div>
